version: 0.2
phases:
  install:
    commands:
      - echo Installing Node.js dependencies
      - npm install
  build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - '**/*'
