version: 0.2

phases:
  install:
    commands:
      - echo Installing Node.js and dependencies
      - npm install
  build:
    commands:
      - echo Making deployment scripts executable
      - chmod +x scripts/*.sh
      - echo Build completed successfully

artifacts:
  files:
    - '**/*'
